### ISSUE TITLE
dynamic library windows

### ISSUE THREAD

**Issue by BPplays** [gen2brain/webp#1]
im having trouble using the dynamic/shared library on windows im not sure where to get libwebp.dll or where to put it

**Comment by gen2brain** [comment]
Hi, sorry, no idea about Windows. This is for issues with this project, I cannot and don't want to provide support for user issues.

**Comment by BPplays** [comment]
@gen2brain even if i grab a libwebp.dll from freecad it won't load it even in the same folder. im not sure if that counts as a user issue. p.s. im not very familiar with how windows loads dlls
```
-> .\bin\balanced_crop.exe
cannot load library libwebp.dll: The specified module could not be found.

-> eza -l .\bin
-a--- 7.4M  6 Jul 11:03 balanced_crop.exe
-a--- 377k 14 Sep  2023 libwebp.dll
```

**Comment by gen2brain** [comment]
libwebp have dependencies that you are missing, libhighway I think?

**Comment by BPplays** [comment]
@gen2brain by libhighway do you mean [this](https://github.com/google/highway)? even with hwy.dll from `vcpkg install highway` it still won't load it. i've also got libwebp dlls building now and switching over from the one i copied from freecad didn't change anything:
```
-> .\bin\balanced_crop.exe
cannot load library libwebp.dll: The specified module could not be found.

-> eza -l .\bin
-a--- 7.4M  6 Jul 11:03 balanced_crop.exe
-a---  45k  6 Jul 13:23 hwy.dll
-a--- 372k  6 Jul 12:42 libwebp.dll
-a--- 160k  6 Jul 12:42 libwebpdecoder.dll
-a---  20k  6 Jul 12:42 libwebpdemux.dll
-a---  41k  6 Jul 12:42 libwebpmux.dll
```

**Comment by gen2brain** [comment]
Is there something like `ldd` on Windows? Can you see what are the dependencies for some dll?

**Comment by BPplays** [comment]
@gen2brain i used the ldd in MSYS2 and it turns out it needed `libsharpyuv.dll` which comes with `vcpkg install libwebp`. it also comes with libwebp.dll so i suggest anyone try copying from that first before trying to compile libwebp

**Comment by gotoeasy** [comment]
Here you can find the DLL files available for download: https://github.com/d2phap/ImageGlass/tree/develop/Source/Libs/libwebp/x64

<img width="500"  alt="Image" src="https://github.com/user-attachments/assets/864c675a-f277-4121-b8ae-0e53345e9303" />

In my tests, I managed to get it working by placing all four DLL files in a directory included in the %PATH% environment variable. However, the final results—whether in terms of performance or compression efficiency—don’t seem to be significantly better than the WASM approach. In some cases, it even performs slightly worse. That said, on Ubuntu, the improvement is noticeably better.

**Comment by gen2brain** [comment]
Sorry, I do not have time to test on Windows. By now, it should not be a mystery how Windows works and what PureGo is using (I do not think they use anything special besides LoadLibrary), so that is really a Windows issue. It is strange that it performs worse, that sounds like you are not actually using it, there are ways to test and confirm what are you actually using. Can you confirm what you are actually using and which code path is executing?

**Comment by gotoeasy** [comment]
You can easily check whether the DLL is successfully loaded using this test code:
https://github.com/gotoeasy/gsbox/blob/main/cmn/webp_test.go
When the DLL is successfully invoked, it will log: "using libwebp for webp compression - perfect setup"

After testing with different datasets, here are my findings:

Placing all four DLL files in a directory included in the PATH successfully enables the DLL—this was confirmed by renaming the DLL and observing that the test no longer logged the successful loading message.

When using the DLL, compression speed improved in most cases, though not consistently (in my tool gsbox, performance varied depending on block size settings).

In terms of compression results, the output file size difference was minimal.

Thank you very much for this project — it's both convenient and stable to use. I don't believe this is an issue with your code; it might be related to how PureGo handles things, though the impact is very minor. The WASM approach is already quite usable and effective.

**Comment by gen2brain** [comment]
Yes, both methods should use libwebp; one is using the libwebp compiled as wasm, and the other is using the shared library via purego. The difference should be just in the speed, but even with just WASM, it is not that bad.
